### ISSUE TITLE
Changes on threejs not supported

### ISSUE THREAD

**Issue by davidbeijinho** [jeromeetienne/threex.objcoord#3]
im getting this errors

THREE.WebGLRenderer 70
three.js:2309 THREE.Vector3: .getPositionFromMatrix() has been renamed to .setFromMatrixPosition().
three.js:192 THREE.Projector has been moved to /examples/js/renderers/Projector.js.
three.js:196 THREE.Projector: .projectVector() is now vector.project().
threex.objcoord.js:51 Uncaught TypeError: Cannot read property 'x' of undefined

**Comment by jeromeetienne** [comment]
it is because it hasnt yet been ported to the last version of three.js

**Comment by davidbeijinho** [comment]
what version should i use ?

**Comment by jeromeetienne** [comment]
i would say "the one from the examples" but i notice it is r59 so rather old. sorry about that

**Comment by davidbeijinho** [comment]
I dont understand a lot of Threejs, but can i help to update do the last version of three

**Comment by jeromeetienne** [comment]
thanks for proposing! 

i figured the time to explain was higher the time to actually do it. so i did it. 

http://jeromeetienne.github.io/threex.objcoord/examples/basic.html is running on three.js r70 now

thanks for reporting

**Comment by davidbeijinho** [comment]
you are the greatest , thanks a lot
